### ISSUE TITLE
session sorunu

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/ReactNativeLoginApp#1]
şuankı örnegi indirdim giriş yapıyorum dedigin gibi uygulama reload yapıyorum en başa donuyor kodlkarda local ip haricinde bir farklılık yapmadım sorun nedir acaba

**Comment by abdurrahmanekr** [comment]
index.php dosyasında session_ticket parametresini göndermeniz gerekir. Onu gönderiyor musunuz ?

**Comment by ahmetozalp** [comment]
bunun kontrolunu nerden yapabilirim gidiyormu gitmiyormu diye

**Comment by abdurrahmanekr** [comment]
src/pages/login-page/login-page.js dosyasında ajaxtan dönen cevap kontrol ediliyor
```javascript
if (res.session_ticket)
	setSessionTicket(String(res.session_ticket));
```
Burada gelmesse doğal olarak tekrar giriş yapınca tekrar login'e atıyor
service tarafında kullanıcıya cevap dönderirken:
```php
echo json_encode(["result" => 1, "session_ticket" => rand()]);
``` 
şeklince eklenmesi gerekir

**Comment by ahmetozalp** [comment]
teşşekur ederim php de die uzerindekı satırı alttakı kod ile degiştidim güncellemeyi unumuşum :)

`echo json_encode(["result" => 1, "session_ticket" => rand()]);`
