### ISSUE TITLE
sana nasıl ulaşabilirim anlık olarak

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/ReactNativeLoginApp#2]
merhaba anlık sohbet etmek ve 1-2 soru sormak için nasıl ulaşırım acbaa

**Comment by abdurrahmanekr** [comment]
Anlık olarak çoğunlukla müsait olmuyorum ama [buradan](https://github.com/abdurrahmanekr/bana-istedigini-sor) soru sorabilirsin. Github'da çoğunlukla müsait olurum twitter facebook var ama  oralardan iş gereği takılamıyorum. Ama dediğin gibi eğer 1, 2 soru varsa https://twitter.com/abdurrahmanekr
