### ISSUE TITLE
react-native 

### ISSUE THREAD

**Issue by semihagungor** [abdurrahmanekr/ReactNativeLoginApp#5]
merhabalar react-native öğrenip proje geliştirmek istiyorum. videolarınızı izleyip makalelerinizi okudum. İngilizce çok fazla bilmediğim için açıkçası kaynakları etkili bir şekilde kullanamıyorum. daha önce bir platformda native veya hybrid uygulama geliştiremedim. anlayacağınız bu işte çok çok yeniyim ,öğrenciyim ve öğrenmek istiyorum. react-native ile sunucu bağlantısı nasıl yaparım? api ile veri çekip nasıl işlerim? react-native bize kelime işleme gibi özellikler sağlıyor mu? aklım da bir çok soru var bunlar sadece bir kaçı sorularımı maruz görüp yardımlarınızı esirgemezseniz memnun olurum.

**Comment by abdurrahmanekr** [comment]
@smhasmha merhaba, bu sorunun aynısını [buraya](https://github.com/abdurrahmanekr/bana-istedigini-sor) açar mısın ? tüm soru takiplerini orada yönetmek istiyorum. Yakın zamanda cevap vereceğim
