### ISSUE TITLE
Tab Sayfası çok karışık olmuş

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/ReactNativeLoginApp#6]
Merhaba tab sayfasını 2 gundur mantıgını çözemedim dersem yeridir yani import olarak sayfaları kullanmak istiyorum ben örnek vermek gerekirse newstab adındakı yer gibi ilk açılan sayfada import olsun src/pages/main-page/ sayfası router gibi olsa çok güzel olurdu son olarak tab ın ustune bir navigation atmak istedim ama navigation u da sekme gibi goruyor nereye atarsam atıyım 

Not: navigation sabih kalcak yana dogru sekmeler kaysa bile.

[![N|Solid](https://image.ibb.co/cCCeC5/Ekran_Resmi_2017_07_29_13_09_48.png)](https://nodesource.com/products/nsolid)

kullandıgım navigation: http://shoutem.github.io/docs/ui-toolkit/components/navigation-bar

son olarak şöyle bir uyarı alıyorum:

[![N|Solid](https://preview.ibb.co/k9MHzk/Ekran_Resmi_2017_07_29_13_10_09.png)](https://nodesource.com/products/nsolid)

**Comment by abdurrahmanekr** [comment]
Şimdi başlangıçta söylediklerinden anladığım **not** kısmı. Bunu yapmak için main-page.js dosyasında bunun yerine:
```javascript
render() {
    return(
        <ScrollableTabView>
            ...
        </ScrollableTabView>
    );
}
```
Şunu kullanman gerekir:
```javascript
render() {
    return(
        <View>
            <NavigationBar/>
            <ScrollableTabView>
                ...
            </ScrollableTabView>
        <View/>
    );
}
```
Böylelikle sekmeler değişse bile navigator aynı yerde kalır. En sonda verdiği hata ise react'in döngüsel yerlerde benzersiz elementler istemesinden kaynaklanıyor. Bu benzersizliği sağlamak için **key** propery'sine benzersiz bir alan geçmen gerekiyor. Örneğin 
```javascript
list.map((x, i) => (
    <View key={i}></View>
))
```
Başlangıçtaki olayı daha anlaşılır bir şekilde anlatabilir misin?

**Comment by ahmetozalp** [comment]
[![N|Solid](https://i.hizliresim.com/WQazZ8.png)](https://yandex.com)

```
import React, { Component } from 'react';

import ScrollableTabView from 'react-native-scrollable-tab-view'

import {
	Text,
	View,
	Alert
} from 'react-native'


import { NavigationBar,Title } from '@shoutem/ui'

import NewsTab from './tabs/tab-iki';
import CustomTabBar from './tabs/custom-tab-bar';

export default class MainPage extends Component {

	constructor(props) {
	  	super(props);
	}

	render() {
		return( <View>
				<NavigationBar
					centerComponent={<Title>Uygulama</Title>}
					share={{
						link: 'http://shoutem.github.io',
						text: 'This is the best',
						title: 'Super cool UI Toolkit',
					}}
				/>
				<ScrollableTabView
					tabBarPosition='bottom'
					style={{ flex: 4 }}
					renderTabBar={() => <CustomTabBar />}
					>
					<NewsTab tabLabel='ios-paper' />
					<Text tabLabel='ios-person'>Burası profil</Text>
				</ScrollableTabView>
			</View>
		);
	}
}

```

**Comment by abdurrahmanekr** [comment]
Sorun çözüldü mü?

**Comment by ahmetozalp** [comment]
Ekrana getirdima am pozisyonları çok kotu view içine alınmıyor ScrollableTabView eger alırsam yana dogru kaydırma özelligi gidiyor bende costum-tab-bar.js sayfasındaşöyle bişi yaptım en ustte sabitlemeye çalışyıromNavigationBar ı diger tabıda alt a sabitlemeye çalışyıroum

[![N|Solid](https://i.hizliresim.com/9dAzl3.png)](https://yandex.com)

```
import React from 'react';
import {
	StyleSheet,
	Text,
	View,
	TouchableOpacity,
} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';

import { NavigationBar,Title } from '@shoutem/ui'

const CustomTabBar = React.createClass({
	tabIcons: [],

	propTypes: {
		goToPage: React.PropTypes.func,
		activeTab: React.PropTypes.number,
		tabs: React.PropTypes.array,
	},

	componentDidMount() {
		this._listener = this.props.scrollValue.addListener(this.setAnimationValue);
	},

	setAnimationValue({ value, }) {
		this.tabIcons.forEach((icon, i) => {
			const progress = Math.min(1, Math.abs(value - i))
			icon.setNativeProps({
				style: {
					color: this.iconColor(progress),
				},
			});
		});
	},

	//color between rgb(59,89,152) and rgb(204,204,204)
	iconColor(progress) {
		const red = 59 + (204 - 59) * progress;
		const green = 89 + (204 - 89) * progress;
		const blue = 152 + (204 - 152) * progress;
		return `rgb(${red}, ${green}, ${blue})`;
	},

	render() {
		return <View>
					<NavigationBar
						style={{ flex: 1 }}
						centerComponent={<Title>Uygulama</Title>}
						share={{
							link: 'http://shoutem.github.io',
							text: 'This is the best',
							title: 'Super cool UI Toolkit',
						}}
					/>
			
					<View style={[styles.tabs, this.props.style, ]}>
						{this.props.tabs.map((tab, i) => {
							return <TouchableOpacity key={tab} onPress={() => this.props.goToPage(i)} style={styles.tab}>
								<Icon
									name={tab}
									size={30}
									color={this.props.activeTab === i ? '#ffe800' : 'white'}
									ref={(icon) => { this.tabIcons[i] = icon; }}
								/>
							</TouchableOpacity>;
						})}
					</View>
			</View>;
	},
});

const styles = StyleSheet.create({
	tab: {
		flex: 2,
		alignItems: 'center',
		justifyContent: 'center',
		paddingBottom: 10
	},
	tabs: {
		height: 45,
		flexDirection: 'row',
		paddingTop: 5,
		borderWidth: 1,
		borderTopWidth: 0,
		borderLeftWidth: 0,
		borderRightWidth: 0,
		borderBottomColor: 'rgba(0,0,0,0.05)'
	},
});

export default CustomTabBar;

```

**Comment by abdurrahmanekr** [comment]
render'dan hemen sonra gelen View'a flex: 1 ekleyip dener misin?

**Comment by ahmetozalp** [comment]
https://i.hizliresim.com/5QX06L.png

**Comment by abdurrahmanekr** [comment]
NavigationBar'daki flex'i sil

**Comment by ahmetozalp** [comment]
bir şey degişmedi gene aynı

**Comment by abdurrahmanekr** [comment]
CustomTabBar içine navbar eklemek sağlıklı değil

**Comment by ahmetozalp** [comment]
nereye eklemeliyim ?

**Comment by abdurrahmanekr** [comment]
İlk attığım şekilde dursun fakat oradaki view'a flex: 1 ekle

**Comment by ahmetozalp** [comment]
kaydırma özelligi çalımıyor ama o şekılde

**Comment by abdurrahmanekr** [comment]
ss atabilir misin?

**Comment by ahmetozalp** [comment]
sen mükmmelsin çalıştı en sonunda https://i.hizliresim.com/PrNdgO.png contant içinde de gosterbilirsem yazıları tamamdır :)

**Comment by abdurrahmanekr** [comment]
O zaman [çalsın davul çalsın](https://www.youtube.com/watch?v=6fq8hNdkF5s&feature=youtu.be&t=50s) 😄

**Comment by ahmetozalp** [comment]
Hahaa teşşekkur ederim tekrar bir issue daha açıcam bu biraz farklı bir şey destegine ihtiyacım var cidden :)

**Comment by ahmetozalp** [comment]
Bunu aldık yukarı iyi hoş ama ust kısma tıklanmıyor :D

**Comment by ahmetozalp** [comment]
sorunu çözdüm
