### ISSUE TITLE
React Native Array

### ISSUE THREAD

**Issue by hulusiM** [abdurrahmanekr/ReactNativeLoginApp#9]
**Üstad Merhabalar,
- data.service.js sayfanın içerisinde 2 adet dizi var ve bunlar başka sayfalarda kullanılıyor. Bunları db bağlantısıyla nasıl doldurabilirim ?** 

```
export const menuItems = [
  {
    thumb: 'lighthouse_lindau',
    index: 1,
    label: 'Lindau Lighthouse, Germany',
  },
  {
    thumb: 'lighthouse_fanad',
    index: 2,
    label: 'Fanad Lighthouse, Ireland'
  }];

export const lighthouses = [
  {
    index: 1,
    title: 'Lindau Lighthouse, Germany',
    image: 'lighthouse_lindau',
    photo: 'Andreas Flohr',
    url: 'http://www.flickr.com/photos/picture4it/5212861056/',
    content: 'The southernmost lighthouse in Germany, the Lindau Lighthouse is locaed on Lake Constance, Lindau. It was completed in 1856, when it took over the port’s previous light station in the Mangtrum Tower, constructed in 1230. The 108 foot tall structure is quite unique among lighthouses because it also houses a massive clock that can be viewed from the city.'
  },
  {
    index: 2,
    title: 'Fanad Lighthouse, Ireland',
    image: 'lighthouse_fanad',
    photo: 'myheimu',
    url: 'http://www.flickr.com/photos/myheimu/7996342794/',
    content: 'After a large ship sank in their waters in 1804, the residents of the Fanad peninsula started to demand a lighthouse be built on the Fanad Head. In 1818, the 90 foot structure was completed and lit. In 1909, a new, brighter light was installed that operated on a weight-driven clockwork rotation machine, built to display six flashes every fifteen seconds. Eventually, this apparatus was replaced in 1975, when the light was converted to electric power.'
  }];
```

**Comment by MuhammetYavuzCayli** [comment]
Merhabalar, öncelikle nodejs gibi bir api teknolojisi kullanıyorsan, this.state içerisine data:[] oluşturabilir ve fetch methoduyla çekip kullanabilirsin. Localhost taysan fetch içerisine pc ip ni vermelisin
Örn:
Fetch("http://192.168.x.xxx",{method:"GET"})
.then((res)=> res.json())
.then(resData)=>{
this.setState({data=resData})
}) 
Gibi.

**Comment by hulusiM** [comment]
@MuhammetYavuzCayli cevap için teşekkürler,
Buradaki sayfa içinde güncelleme yapmam gerekiyor 
https://github.com/darde/react-native-sidemenu/blob/master/app/data.service.js

**Comment by MuhammetYavuzCayli** [comment]
Link 404 hatası verdi jsi göremiyorum ama dbden gelen dizi ile elindeki sabit diziyi birleştirerek güncellemek için this.setState içerisinde;
data:[...lighthouses, ...resData]
Diyerek birleştirebilirsin.

**Comment by hulusiM** [comment]
@MuhammetYavuzCayli linke şimdi bakabilirsin

**Comment by hulusiM** [comment]
class yapısını kullanmadan linkteki sayfa içerisinde componentWillMount gibi bi fonksiyon var mı

**Comment by abdurrahmanekr** [comment]
@hulusimizrak şöyle yapabilirsin. Ben genellikle öyle kullanıyorum global olarak istediğim yerde import ederek onu doldurup işlem yapabiliyorum. export ederken bir array şeklinde değilde class türünde export edersen değerleri güncelleme yapabilirsin. ör:
```javascript
class DataService {
    constructor(){
        this.menuItems = [{
            thumb: 'lighthouse_lindau',
            index: 1,
            label: 'Lindau Lighthouse, Germany',
        }, {
            thumb: 'lighthouse_fanad',
            index: 2,
            label: 'Fanad Lighthouse, Ireland'
        }];
    }
}

export default new DataService();
```
Şimdi bu dosyayı import ettiğin her yerde DataService.menuItems dediğin zaman sana değeri gelir aynı zamanda bu değerleri değiştirebilirsin. ör:
```javascript
import React, { Component } from 'react';

import {
    View,
    Text,
} from 'react-native';

import DataService from './DataService';

export class App extends Component {
    constructor(props) {
        super(props);
        this.list = DataService.menuItems || [];
    }

    render() {
        return (
            <View>
                {
                    this.list.map(x => (
                        <Text>{x.label}</Text>
                    ))
                }
            </View>
        );
    }
}
```
Bir de issue açarken eğer kod eklemek istiyorsan kodları düzgün bir şekilde ``` arasında yazarsan görüntü açısından anlaşılır olur. Bu da bir tavsiye idi :)

**Comment by hulusiM** [comment]
@abdurrahmanekr eyvallah üstadım :)
